### ISSUE TITLE
stabilizing 

### ISSUE THREAD

**Issue by yosun** [huihut/Facemoji#1]
have you played with stabilizing the tracking from opencvforunity dlib package? it is rather shaky

**Comment by huihut** [comment]
It does shake, especially eyes and eyebrows.  There are two reasons for this: 
* One is that each frame of facial landmark detected by dlib will be offset, it can only be optimized by improving the Dlib face detection algorithm.
* The other is the setting of the model parameters. I tried to adjust the parameters to stabilize it. [v1.3](https://github.com/huihut/Facemoji/commit/7152099ec424fc019d416ec90a70b9a494f835cb#diff-83c3e0d0dc4346851a443e2472bd356dL288) But the best solution should be to set parameters based on the user's face pattern. you can change the parameters in the [live2DModelUpdate](https://github.com/huihut/Facemoji/blob/master/Assets/Scripts/WebCamTextureLive2DSample.cs#L292).

**Comment by yosun** [comment]
have you tried to implement the kalman filter or other filters to try to stabilize it?

**Comment by huihut** [comment]
Well, I haven't tried, maybe I can try it, thx!
